config:
  default: true

  # Allow long lines in prose (common in technical blogs)
  MD013: false

  # Allow duplicate headings (sometimes ok across sections)
  MD024: false

  # Allow inline HTML (Minimal Mistakes sometimes uses it)
  MD033: false

  # Allow  title as heading, date as metadata
  MD036: false


globs:
  - "**/*.md"
ignores:
  - "_site/**"
  - "vendor/**"
  - "node_modules/**"
